### ISSUE TITLE
ncall is deprecated

### ISSUE THREAD

**Issue by dvdvck** [karthikv/nodefront#31] opened 2012-11-26 23:42 UTC
Hi there,
I got this output when I run 

```
nodefront serve 
ncall is deprecated, use ninvoke instead. Error
    at Object.exports.nextTick [as ncall] (/opt/local/lib/node_modules/nodefront/node_modules/q/q.js:314:85)
    at Server.<anonymous> (/opt/local/lib/node_modules/nodefront/commands/serve.js:137:9)
    at Server.EventEmitter.emit (events.js:99:17)
    at HTTPParser.parser.onIncoming (http.js:1807:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:111:23)
    at Socket.socket.ondata (http.js:1704:22)
    at TCP.onread (net.js:403:27)
```

these are the versions

```
node --version
v0.8.14
nodefront --version
1.0.4
```

**Comment by ForbesLindesay** [comment] 2012-11-27 04:49
That's an issue caused by an update in Q and should be pretty quick to fix.

**Comment by anthonyringoet** [comment] 2012-12-06 20:59
Same here on 
node v0.8.7 and nodefront v1.0.4

**Comment by rosner** [comment] 2012-12-06 22:03
+1 with latest versions

**Comment by karthikv** [comment] 2012-12-22 22:29
Apologies for the delay. I've taken care of this by freezing Q at version 0.8.10. This change has been released in nodefront v1.0.5. Please re-open this issue if you continue to experience problems.

**Closed as completed by karthikv** 2012-12-22 22:29 UTC

**Comment by tborychowski** [comment] 2013-07-22 10:04
I started getting this issue after socket.io update, when I run: nodefront serve
node version: 0.10.13
nodefront 1.0.7
socket.io: 0.9.16

**Comment by tborychowski** [comment] 2013-07-26 09:24
Issue still persist in node v0.10.15

**Comment by karthikv** [comment] 2013-07-29 04:53
What's the backtrace you're getting? You said you're seeing this issue after a socket.io update, so perhaps this is on socket.io's end.

**Comment by tborychowski** [comment] 2013-07-29 14:07
Hi,
Here's the log.
The strange thing is - that it does "serve" the project (seems to work as before) but it still prints these errors...
I don't know enough to say what's causing the issue. I guess it is possible that this is socket.io's fault :-)
Anyways, thanks for your help and excellent project!

```
ncall is deprecated, use ninvoke instead. Error
    at Object.ncall (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:314:85)
    at exists (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\fs.js:8:14)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:8:23
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:27:20
    at Array.map (native)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:26:26
    at _fulfilled (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:830:54)
    at resolvedValue.promiseSend.done (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:860:30)
    at makePromise.promise.promiseSend (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:487:13)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:854:23
ncall is deprecated, use ninvoke instead. Error
    at Object.ncall (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:314:85)
    at exists (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\fs.js:8:14)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:8:23
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:27:20
    at Array.map (native)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:26:26
    at _fulfilled (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:830:54)
    at resolvedValue.promiseSend.done (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:860:30)
    at makePromise.promise.promiseSend (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:487:13)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:854:23
ncall is deprecated, use ninvoke instead. Error
    at Object.ncall (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:314:85)
    at exists (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\fs.js:8:14)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:8:23
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:27:20
    at Array.map (native)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:26:26
    at _fulfilled (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:830:54)
    at resolvedValue.promiseSend.done (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:860:30)
    at makePromise.promise.promiseSend (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:487:13)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:854:23
ncall is deprecated, use ninvoke instead. Error
    at Object.ncall (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:314:85)
    at exists (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\fs.js:8:14)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:8:23
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:27:20
    at Array.map (native)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:26:26
    at _fulfilled (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:830:54)
    at resolvedValue.promiseSend.done (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:860:30)
    at makePromise.promise.promiseSend (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:487:13)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:854:23
ncall is deprecated, use ninvoke instead. Error
    at Object.ncall (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:314:85)
    at exists (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\fs.js:8:14)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:8:23
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:27:20
    at Array.map (native)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:26:26
    at _fulfilled (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:830:54)
    at resolvedValue.promiseSend.done (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:860:30)
    at makePromise.promise.promiseSend (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:487:13)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:854:23
ncall is deprecated, use ninvoke instead. Error
    at Object.ncall (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:314:85)
    at exists (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\fs.js:8:14)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:8:23
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:27:20
    at Array.map (native)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:26:26
    at _fulfilled (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:830:54)
    at resolvedValue.promiseSend.done (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:860:30)
    at makePromise.promise.promiseSend (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:487:13)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:854:23
ncall is deprecated, use ninvoke instead. Error
    at Object.ncall (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:314:85)
    at exists (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\fs.js:8:14)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:8:23
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:27:20
    at Array.map (native)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:26:26
    at _fulfilled (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:830:54)
    at resolvedValue.promiseSend.done (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:860:30)
    at makePromise.promise.promiseSend (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:487:13)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:854:23
ncall is deprecated, use ninvoke instead. Error
    at Object.ncall (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:314:85)
    at exists (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\fs.js:8:14)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:8:23
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:27:20
    at Array.map (native)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:26:26
    at _fulfilled (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:830:54)
    at resolvedValue.promiseSend.done (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:860:30)
    at makePromise.promise.promiseSend (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:487:13)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:854:23
ncall is deprecated, use ninvoke instead. Error
    at Object.ncall (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:314:85)
    at exists (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\fs.js:8:14)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:8:23
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:27:20
    at Array.map (native)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:26:26
    at _fulfilled (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:830:54)
    at resolvedValue.promiseSend.done (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:860:30)
    at makePromise.promise.promiseSend (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:487:13)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:854:23
ncall is deprecated, use ninvoke instead. Error
    at Object.ncall (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:314:85)
    at exists (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\fs.js:8:14)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:8:23
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:27:20
    at Array.map (native)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:26:26
    at _fulfilled (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:830:54)
    at resolvedValue.promiseSend.done (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:860:30)
    at makePromise.promise.promiseSend (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:487:13)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:854:23
ncall is deprecated, use ninvoke instead. Error
    at Object.ncall (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:314:85)
    at exists (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\fs.js:8:14)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:8:23
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:27:20
    at Array.map (native)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:26:26
    at _fulfilled (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:830:54)
    at resolvedValue.promiseSend.done (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:860:30)
    at makePromise.promise.promiseSend (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:487:13)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:854:23
ncall is deprecated, use ninvoke instead. Error
    at Object.ncall (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:314:85)
    at exists (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\fs.js:8:14)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:8:23
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:27:20
    at Array.map (native)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\lib\utils.js:26:26
    at _fulfilled (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:830:54)
    at resolvedValue.promiseSend.done (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:860:30)
    at makePromise.promise.promiseSend (C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:487:13)
    at C:\Users\Tom\AppData\Roaming\npm\node_modules\nodefront\node_modules\commander-config\node_modules\q\q.js:854:23
Serving your files at http://127.0.0.1:3000/.
   info  - socket.io started
```

**Comment by karthikv** [comment] 2013-07-30 04:36
This is merely a warning, and not an error; everything will continue to work fine.

This looks to be entirely in commander-config. @ForbesLindesay, can you update your calls or freeze the version of q to 0.8.10?
